#Connection url for connection in the DatabaseView:
#  jdbc:mysql://0.0.0.0:13306/DOCKERDB, login=root, password=root
#App is available at: http://localhost:<local-port>/entitybus/post
version: "3.8"
networks:
  test:

services:
  core-apis:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - test
